# NumPy Array Functions  
NumPy array functions are the built-in functions provided by NumPy that allow us to create and manipulate arrays, and perform different operations on them.  

## Common NumPy Array Functions
There are many NumPy array functions available but here are some of the most commonly used ones.

---
Array Operations	Functions
Array Creation Functions	np.array(), np.zeros(), np.ones(), np.empty(), etc.
Array Manipulation Functions	np.reshape(), np.transpose(), etc.
Array Mathematical Functions	np.add(), np.subtract(), np.sqrt(), np.power(), etc.
Array Statistical Functions	np.median(), np.mean(), np.std(), and np.var().
Array Input and Output Functions	np.save(), np.load(), np.loadtxt(), etc.
---

In [5]:
import numpy as np

array1 = np.array([1, 3, 5, 2, 4, 6, 7, 9, 8, 10])
print("np.array():\n", array1)
array2 = np.reshape(array1, (2, 5))
print("np.reshape():\n", array2)
array3 = np.transpose(array2)
print("np.transpose():\n", array3)

np.array():
 [ 1  3  5  2  4  6  7  9  8 10]
np.reshape():
 [[ 1  3  5  2  4]
 [ 6  7  9  8 10]]
np.transpose():
 [[ 1  6]
 [ 3  7]
 [ 5  9]
 [ 2  8]
 [ 4 10]]
